# Generated by Django 4.0.5 on 2023-01-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmanic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField()),
                ('p_category', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('rating', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('count', models.BigIntegerField()),
            ],
        ),
    ]
